services:
  postgres:
    image: postgres:15
    container_name: teste_tecnico_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./insert_data.sql:/docker-entrypoint-initdb.d/02_insert_data.sql

#  app:
#    build: ../.
#    container_name: node_app
#    ports:
#      - "3000:3000"
#    depends_on:
#      - postgres
#    networks:
#      - app-network

volumes:
  postgres_data:

#networks:
#  app-network:
#    driver: bridge
